---
- hosts: logger
  become: yes

  roles:
    - geerlingguy.logstash  # to use its handler

  tasks:

    - name: Remove legacy configuration (coming from the logstash role)
      file:
        path: "{{ item }}"
        state: absent
      with_items:
      - /etc/logstash/conf.d/01-beats-input.conf
      - /etc/logstash/conf.d/10-syslog.conf
      - /etc/logstash/conf.d/11-nginx.conf
      - /etc/logstash/conf.d/12-apache.conf
      - /etc/logstash/conf.d/14-solr.conf
      - /etc/logstash/conf.d/15-drupal.conf

    - name: Copy logstash pipeline configuration files.
      copy:
        src: "{{ item }}"
        dest: "/etc/logstash/conf.d/"
        owner: root
        group: root
        mode: 0644
      with_items:
      - files/logstash/02-local-syslog-input.conf
  #      - files/logstash/03-local-apache-logs-input.cfg
      - files/logstash/04-remote-syslog-input.conf
      - files/logstash/10-syslog-filter.conf
      - files/logstash/30-elasticsearch-output.conf
      notify: restart logstash


