---
kibana_server_name: logs
kibana_username: kibana
kibana_password: password

logstash_monitor_local_syslog: false
logstash_ssl_key_file: elk-vagrant-example.key
logstash_ssl_certificate_file: elk-vagrant-example.crt

logstash_forwarder_files:
  - paths:
      - /var/log/auth.log
    fields:
      type: syslog
